version: '3'

services:
  nginx:
    image: nginx:this
    container_name: nginx
    build: nginx
    ports:
      - 2233:80
    volumes:
      - ./nginx/conf/:/etc/nginx/
      - ./nginx/modules:/modules